import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

import GlobalDialogs from './components/globaldialog';
import GlobalProvider from './components/globalprovider';
import GlobalDrawer from './components/globaldrawer';
import GoogleLogin from './components/googlelogin';
import { getDictionary } from './components/dictionary';
import Toast from '../components/toast';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = 'en' as const;
  const dict = await getDictionary(lang);
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <GlobalProvider i18={dict}>
          {children}
          <Toast />
          <GlobalDialogs />
          <GlobalDrawer />
          <GoogleLogin />
        </GlobalProvider>
      </body>
    </html>
  );
}
